Date: 20200923
File: portage-latest.tar.xz
Verify result:
gpg: Signature made Wed Sep 23 00:56:21 2020 UTC
gpg:                using RSA key E1D6ABB63BFCFB4BA02FDF1CEC590EEAC9189250
gpg: Good signature from "Gentoo Portage Snapshot Signing Key (Automated Signing Key)" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: DCD0 5B71 EAB9 4199 527F  44AC DB6B 8C1F 96D8 BF6D
     Subkey fingerprint: E1D6 ABB6 3BFC FB4B A02F  DF1C EC59 0EEA C918 9250

gpgsig:
-----BEGIN PGP SIGNATURE-----

iQKTBAABCgB9FiEE4dartjv8+0ugL98c7FkO6skYklAFAl9qnTVfFIAAAAAALgAo
aXNzdWVyLWZwckBub3RhdGlvbnMub3BlbnBncC5maWZ0aGhvcnNlbWFuLm5ldEUx
RDZBQkI2M0JGQ0ZCNEJBMDJGREYxQ0VDNTkwRUVBQzkxODkyNTAACgkQ7FkO6skY
klA82w/+O8vkbw9AuzdXrKTGjrFhGhYNeQ7KJD56K0afZy5A7s6VY6XYEjY4Dgg3
qBn3ToWIPN7bqFVrGJqEcehZHbJJfCraW5zVdzsZG/INKsQP0MOrZj4L2SgJMoAp
vIFe84kiQxUePGg4Qe9YbUzkllEJ9v/I5xN44aEks5taAe+vsbl2p8/zzgrAIQye
ppGMramWBy9xQ/IhsZqZP1c2tB97LPTeOuUwwXw/M9fjUz4Dzswa0w4Ld986COBT
0dcWhwxeA9xTUR5HStsHd3G3RFVGBVa174YNChyKK9QeBwfuzuhCkDEc7KPw9NFZ
5X6OOpc5U9+dv5s0f6ZNsDhd+fdo2C4AHMTu+wIriyu1AY+we3tcURJ5jbwh0Ybq
8qN5ihLfZJ0ywJZxs+MhziWf7BeZ9oswf5dZnaeBuiD0xfE5IdtgBAUEi9eg/rqF
txUQKaeUyOVvTgr9os0yj2IwFtnw5gIFma+KqrY00MJnjqYFZ4uzLi1+4X+l2G5p
Y1eyko2YrA4MWFvC3OTfBBEJarZug3Ln99lojd/BmaOp9/p2LzR+YAXzqNg2tIet
ODP4BN/VTd65b3lCYCsaOTurneN3iqUTSGmO1Ioj37tRvQubF0u+19ZVRW0MWIif
QLyRyeCuAgxY+yBaBS0AgLLDjT4y4yFzhQIWEQM02Rmix+i/P5M=
=YspK
-----END PGP SIGNATURE-----

diff --git a/metadata/install-qa-check.d/60distutils-use-setuptools b/metadata/install-qa-check.d/60distutils-use-setuptools
--- a/metadata/install-qa-check.d/60distutils-use-setuptools
+++ b/metadata/install-qa-check.d/60distutils-use-setuptools
@@ -4,33 +4,6 @@
 # QA check: verify correctness of DISTUTILS_USE_SETUPTOOLS
 # Maintainer: Python project <python@gentoo.org>
 
-get_expected_distutils_use_setuptools() {
-	local sitedir=${D}$(python_get_sitedir)
-	local egg new_expected
-	while read -d $'\0' -r egg; do
-		if [[ -f ${egg} ]]; then
-			# if .egg-info is a file, it's plain distutils
-			new_expected=no
-		elif grep -q -s -F '[console_scripts]' "${egg}"/entry_points.txt
-		then
-			# entry_points == we need rdepend
-			new_expected=rdepend
-		elif grep -q -E -s '^setuptools' "${egg}"/requires.txt
-		then
-			# explicit rdepend in package metadata
-			new_expected=rdepend
-		else
-			new_expected=bdepend
-		fi
-
-		if [[ ${expected} && ${new_expected} != ${expected} ]]; then
-			expected=integrity-error
-		else
-			expected=${new_expected}
-		fi
-	done < <(find "${sitedir}" -name '*.egg-info' -print0)
-}
-
 distutils_use_setuptools_check() {
 	# applicable only to ebuilds inheriting distutils-r1
 	[[ ${_DISTUTILS_R1} ]] || return
@@ -39,21 +12,60 @@ distutils_use_setuptools_check() {
 	# pyproject.toml is verified by using it
 	[[ ${DISTUTILS_USE_SETUPTOOLS} == pyproject.toml ]] && return
 
-	local expected
-	_distutils-r1_run_foreach_impl get_expected_distutils_use_setuptools
+	local expected=()
+	for impl in "${_PYTHON_SUPPORTED_IMPLS[@]}"; do
+		local EPYTHON PYTHON
+		_python_export "${impl}" EPYTHON PYTHON
+		[[ -x ${PYTHON} ]] || continue
+		local sitedir=${D}$(python_get_sitedir)
+		if [[ -d ${sitedir} ]]; then
+			local egg new_expected
+			while read -d $'\0' -r egg; do
+				if [[ -f ${egg} ]]; then
+					# if .egg-info is a file, it's plain distutils
+					new_expected=no
+				elif grep -q -s -F '[console_scripts]' \
+						"${egg}"/entry_points.txt
+				then
+					# entry_points == we need rdepend
+					new_expected=rdepend
+				elif grep -q -E -s '^setuptools' \
+						"${egg}"/requires.txt
+				then
+					# explicit rdepend in package metadata
+					new_expected=rdepend
+				else
+					new_expected=bdepend
+				fi
 
-	if [[ ${expected} == integrity-error ]]; then
-		eerror "DISTUTILS_USE_SETUPTOOLS integrity error!"
-		eerror "expected was:    ${expected}"
-		eerror "new_expected is: ${new_expected}"
+				if ! has "${new_expected}" "${expected[@]}"; then
+					expected+=( "${new_expected[@]}" )
+				fi
+			done < <(find "${sitedir}" -name '*.egg-info' -print0)
+		fi
+	done
+
+	# at this point, expected can contain: no bdepend rdepend
+	if [[ ${#expected[@]} -gt 1 ]] && has no "${expected[@]}"; then
+		# 'no' and '[rb]depend' are mutually exclusive
+		eerror "The package seems to have used distutils and setuptools simultaneously."
+		eerror "This could mean the package has bad conditions:"
+		eerror "https://dev.gentoo.org/~mgorny/python-guide/distutils.html#conditional-distutils-setuptools-use-in-packages"
 		eerror "Please report a bug about this and CC python@"
-	elif [[ ${DISTUTILS_USE_SETUPTOOLS} != ${expected} ]]; then
-			local def=
-			[[ ${DISTUTILS_USE_SETUPTOOLS} == bdepend ]] && def=' (or unset)'
+	elif [[ ${#expected[@]} -gt 0 ]]; then
+		# bdepend+rdepend=rdepend
+		has rdepend "${expected[@]}" && expected=( rdepend )
+		# at this point, expected should have exactly one value
+		[[ ${#expected[@]} -eq 1 ]] || die "integrity error"
 
-			eqawarn "DISTUTILS_USE_SETUPTOOLS value is probably incorrect"
-			eqawarn "  have:     DISTUTILS_USE_SETUPTOOLS=${DISTUTILS_USE_SETUPTOOLS}${def}"
-			eqawarn "  expected: DISTUTILS_USE_SETUPTOOLS=${expected}"
+		if [[ ${DISTUTILS_USE_SETUPTOOLS} != ${expected} ]]; then
+				local def=
+				[[ ${DISTUTILS_USE_SETUPTOOLS} == bdepend ]] && def=' (or unset)'
+
+				eqawarn "DISTUTILS_USE_SETUPTOOLS value is probably incorrect"
+				eqawarn "  have:     DISTUTILS_USE_SETUPTOOLS=${DISTUTILS_USE_SETUPTOOLS}${def}"
+				eqawarn "  expected: DISTUTILS_USE_SETUPTOOLS=${expected}"
+		fi
 	fi
 }
 
